spring:
  application:
    name: spring-security-jwt
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: ims
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
application:
  security:
    jwt:
      secret-key: